import type { UiCopy } from "./types";

export const en: UiCopy = {
  product: "Leady",
  nav: {
    home: "Home",
    setup: "Setup",
    chat: "Simulator",
    leads: "Customers",
    inbox: "Inbox",
    channels: "Channels",
    ops: "Ops",
    admin: "Admin",
  },
  langToggle: { he: "עברית", en: "English", uiLanguage: "UI language" },
  themeToggle: { appearance: "Appearance", system: "Match system", light: "Light", dark: "Dark" },
  actingAs: "Acting as {name}",
  stopActing: "Stop acting as tenant",
  page: {
    homeTitle: "Dashboard",
    homeBlurb: "Manage leads, conversations, and channels in one place.",
    homeSetup: "Finish Setup so the agent can greet with your intro.",
    homeChat: "Open simulator",
    setupTitle: "Business setup",
    setupBlurb: "Upload a knowledge file first - we extract setup fields, then you review business details.",
    chatTitle: "Agent simulator",
    chatBlurb: "You are messaging as the customer. Live WhatsApp is on Channels.",
    leadsTitle: "Customers",
    inboxTitle: "Inbox",
    channelsTitle: "Channels",
    opsTitle: "Ops",
    adminTitle: "Tenant admin",
  },
  home: {
    quickSetup: "Agent & knowledge setup",
    quickChat: "Customer simulation",
    quickLeads: "Customer list",
    quickInbox: "Tasks to approve",
    quickChannels: "Connect WhatsApp",
    tenantLabel: "Business",
    journeyTitle: "Your workflow",
    journeyBlurb: "Setup → Channels → Chat → Customers → Inbox",
    stepSetup: "Business & agent setup",
    stepChannels: "Connect WhatsApp",
    stepChat: "Test chat",
    stepLeads: "Manage customers",
    stepInbox: "Approve tasks",
    ctaInbox: "Review waiting tasks",
    ctaConnect: "Connect WhatsApp",
    whatsappOk: "WhatsApp connected",
    whatsappOff: "WhatsApp not connected",
  },
  common: {
    save: "Save",
    saving: "Saving…",
    next: "Next",
    back: "Back",
    extract: "Extract details",
    extracting: "Extracting…",
    empty: "-",
    pending: "pending",
    demo: "demo",
    delete: "Delete",
    confirmDeleteDemo: "Delete this demo lead and its conversation?",
    name: "Name",
    channel: "Channel",
    status: "Status",
    stage: "Stage",
    visit: "Visit",
    intent: "Intent",
    openLead: "Open lead",
    noLeads: "No leads yet. Start from the simulator.",
    nothingWaiting: "Nothing waiting.",
    comingSoon: "Coming soon",
    connectWhatsApp: "Connect WhatsApp",
    reconnectWhatsApp: "Reconnect",
    connectInstagram: "Connect Instagram",
    reconnectInstagram: "Reconnect",
    instagram: "Instagram",
    whatsapp: "WhatsApp",
    instagramProfile: "Instagram profile",
    zernioMissing: "Set ZERNIO_API_KEY in .env",
    connectedNumber: "Connected number",
    accountId: "Account id",
    createTenant: "Create tenant",
    tenantName: "Business name",
    tenantPhone: "Phone",
    openAsTenant: "Open as tenant",
    adminUnlock: "Enter the admin secret",
    adminSecret: "Secret",
    unlock: "Unlock",
    visitsWaiting: "Visits waiting for approval",
    captured: "Captured data",
    conversation: "Conversation",
    flow: "Conversation style",
    advanced: "Advanced",
    customers: "Customers",
    newChat: "New chat",
    knowledge: "Knowledge",
    business: "Business",
    done: "Done",
    editDetails: "Edit details",
    visitsTab: "Visits",
    decisionsTab: "Decisions",
    meetingsTab: "Meetings",
    noVisits: "No visits yet.",
    noDecisions: "No decisions waiting.",
    noMeetings: "No confirmed meetings yet.",
    details: "Details",
    close: "Close",
    cancel: "Cancel",
    stepOf: "Step {current} of {total}",
    enabled: "Enabled",
    disabled: "Disabled",
    on: "On",
    off: "Off",
    approve: "Approve",
    decline: "Decline",
    send: "Send",
    sending: "Sending…",
    need: "Need",
    phone: "Phone",
    email: "Email",
    version: "Version",
    menu: "Menu",
    search: "Search",
    all: "All",
    live: "Live",
    lastActive: "Last active",
    staff: "Staff",
    saveFailed: "Save failed",
  },
  status: {
    new: "New",
    open: "Open",
    in_progress: "In progress",
    won: "Won",
    lost: "Lost",
  },
  roles: {
    lead: "Customer",
    agent: "Agent",
    human: "Human",
  },
  chat: {
    emptyThread: "No messages yet. Say hello as the customer.",
    placeholder: "Message as this customer",
    waitingHuman: "Waiting on a human…",
    pausedForHuman: "Paused for a human - continue in",
    startNew: "Start as a new customer or pick one from the list.",
    noIntro: "No intro yet",
    flowLabel: "Conversation style",
    languageLabel: "Agent language",
    sendFailed: "Send failed",
    today: "Today",
    yesterday: "Yesterday",
  },
  onboard: {
    agentLanguageLegend: "Agent language",
    agentLanguageHint: "Controls which language the agent replies in chat.",
    knowledgeHint:
      "Upload a .txt or .md file. We fill name, phone, intro, address, and hours so you can skip typing if they are already in the document.",
    knowledgePlaceholder: "Or paste notes here, then extract.",
    dropzoneIdle: "Drop a .txt / .md file here",
    dropzoneBusy: "Reading the file…",
    dropInvalid: "Drop .txt or .md files only",
    extractFailed: "Could not extract from the file",
    noLlm: "No LLM key configured - fill business details on the next step.",
    saveFailed: "Could not save",
    businessHint: "",
    fieldName: "Business name",
    fieldPhone: "Public phone",
    fieldIntro: "Self-introduction (what the agent says at the start of a chat)",
    fieldIntroPlaceholder: "We help local customers book a visit with the team.",
    fieldAddress: "Address (shown after a visit is requested)",
    fieldAddressPlaceholder: "Street, city",
    fieldHours: "Opening hours (included when asking for a time)",
    fieldHoursPlaceholder: "Sun–Thu 09:00–19:00",
    fieldBookingRequest: "Tentative booking message",
    fieldBookingApproved: "Approved booking message",
    fieldBookingRejected: "Declined booking message",
    templatesHint:
      "Leave empty for language defaults. Placeholders: {{date}} {{time}} {{slot}} {{name}} {{phone}} {{details}} {{need}} {{kind}} {{address}} {{hours}} {{email}}",
    fieldIdleDays: "Reset conversation after idle days",
    idleHint:
      "The first customer message always gets this intro (no AI). After a long quiet period the agent may ask whether to start a fresh conversation — it will not rotate automatically. 0 = never treat silence as a cue.",
    doneHint: "The first message is always your intro. The next message is when the agent starts talking.",
    catalogLegend: "Agent mode",
    capabilitiesLegend: "Capabilities",
    capabilitiesHint: "Turn on what this agent can do. With nothing enabled it only answers from knowledge.",
    bookingStanceLegend: "Booking style",
    collectLegend: "What to collect for a visit",
    collectHint:
      "The agent asks only the checked items. Name and preferred time are always collected. WhatsApp already has their number - leave Phone unchecked unless you also want a typed number.",
    timeAlwaysCollected: "Always collected (required).",
    filledFields: "Filled {count} business fields from the file.",
    insertToken: "Insert",
  },
  catalog: {
    inbox: {
      title: "Assist",
      blurb: "Answer questions; capabilities below control booking and more.",
    },
    faq: {
      title: "FAQ only",
      blurb: "Answer from your intro and files. No transactional capabilities.",
    },
  },
  capabilities: {
    booking: {
      title: "Booking",
      blurb: "Collect visit details and send tentative meeting requests for approval.",
    },
    orders: {
      title: "Orders",
      blurb: "Coming soon — order intake for commerce flows.",
    },
    docs: {
      title: "Documents",
      blurb: "Coming soon — ask customers for documents and hand off for review.",
    },
  },
  bookingStance: {
    passive: {
      title: "When they ask",
      blurb: "Answer first; start booking only after an explicit schedule request.",
    },
    proactive: {
      title: "Nudge toward a visit",
      blurb: "After helping, gently invite them to schedule when it fits.",
    },
  },
  chatLanguage: {
    multi: {
      title: "Match customer",
      blurb: "Reply in Hebrew or English based on what they wrote.",
    },
    he: {
      title: "Hebrew only",
      blurb: "Always reply in Hebrew, even if the customer writes in English.",
    },
    en: {
      title: "English only",
      blurb: "Always reply in English.",
    },
  },
  bookingCollect: {
    time_preference: { title: "Preferred time", blurb: "Day and time for the visit" },
    name: { title: "Name", blurb: "Full name" },
    need: { title: "Need", blurb: "What to cover in the visit" },
    phone: {
      title: "Phone",
      blurb: "Ask when missing; confirm when the chat number can be deduced (WhatsApp).",
    },
    email: { title: "Email", blurb: "For visit confirmation" },
    visit_kind: { title: "Visit kind", blurb: "Type of visit" },
  },
  inbox: {
    decisionLegend: "Decision",
    approveOption: "Approve",
    needInfoOption: "Need more info",
    notePlaceholder: "Note the agent should use",
    complete: "Complete and resume",
    bookingApproval: "Booking approval",
    tasksWaiting: "{count} tasks waiting",
    emptyHint: "When a customer requests a human or visit, the task appears here.",
    generalTask: "Human task",
    openChat: "Open simulator",
    reason: "Reason",
    summaryTitle: "Conversation summary",
    summaryEmpty: "No summary yet - open the chat if you need the full thread.",
    summaryWhen: "When",
    summaryIntent: "Intent",
    declineNoteLabel: "Note for the customer (optional)",
    declineNotePlaceholder: "Appended under the message as “Note from the team”",
    customReplyLabel: "Custom reply (optional — approve only, replaces the template)",
    customReplyPlaceholder: "Leave empty to use the default message",
    newConversation: "End conversation",
    startConversation: "Start a new conversation",
    reopenConversation: "Reopen conversation",
    startDisabledHint: "Conversation ended",
    conversationEnded: "Conversation ended",
    reopenDisabledHint: "Cannot reopen while a newer conversation is open",
    decisionsLockedHint: "Decisions are locked — a newer conversation was started",
    decisionLogAction: "Action",
    decisionLogWhen: "When",
    decisionLogActor: "Who",
    decisionLogApproved: "Approved meeting",
    decisionLogDeclined: "Declined meeting",
    decisionLogRescheduled: "Suggested another time",
    decisionLogApprovedByCustomer: "Customer confirmed the time",
    decisionLogActorAdmin: "Admin",
    decisionLogActorCustomer: "Customer",
    decisionLogPreviousSlot: "Previous time",
    decisionLogEmpty: "No decisions logged yet",
    markRead: "Mark as read",
    markUnread: "Mark as unread",
    staffPlaceholder: "Write to the customer as staff…",
    historyTitle: "Resolved",
    waitingTitle: "Waiting",
    taskOpen: "Open",
    taskResolved: "Resolved",
    updateDecision: "You can change this decision; a new message is sent on the conversation",
    currentDecision: "Current decision",
    changeDecision: "Change decision",
    awaitingCustomer: "Waiting for customer",
    awaitingCustomerHint: "An alternative time was offered — waiting for the customer to confirm in chat.",
    customerConfirmed: "Customer confirmed",
    reasons: {
      support_unresolved: "The agent could not resolve this and asked for a human.",
      escalation_requested: "The customer asked to speak with a person.",
      asked_for_person: "The customer asked to speak with a person.",
      booking_approval: "Visit booking waiting for approval",
    },
  },
  meeting: {
    approve: "Approve visit",
    decline: "Decline",
    reschedule: "Suggest another time",
    alternativeSlotLabel: "Alternative time for the customer",
    alternativeSlotPlaceholder: "e.g. Thursday at 12:00",
    visitDefault: "visit",
    approved: "Approved",
    rejected: "Declined",
  },
  ops: {
    catalogLegend: "Catalog (re-clones the JSON flow)",
    afterDoneLegend: "After a conversation is done",
    ignoreMessages: "Ignore new messages",
    restartFlow: "Start the flow over",
    fallbackStage: "Switch to fallback stage",
    fallbackStageLabel: "Fallback stage",
    noneOption: "(none)",
    hitlLegend: "Human-in-the-loop",
    allowHuman: "Allow request_human",
    stagesLegend: "Stages allowed to escalate",
    intentsLegend: "Intents that may escalate",
    ownersNeverSee: "Business owners never see this page.",
  },
  flow: {
    start: "Start",
    afterDone: "After done",
    needFields: "Required fields",
    transitions: "Transitions",
    currentStage: "Current stage",
    progress: "Flow progress",
  },
  leadFields: {
    name: "Name",
    need: "Need",
    email: "Email",
    phone: "Phone",
    budget: "Budget",
    intent: "Intent",
    booking: "Booking",
    service: "Service",
    visit_kind: "Visit kind",
    time_preference: "Preferred time",
  },
  meetingKinds: { visit: "Visit", showroom: "Showroom", online: "Online", phone: "Phone call" },
  stages: {
    talk: "Conversation",
    escalate: "Escalate to human",
    done: "Done",
    waiting_human: "Waiting for human",
    collect: "Collect details",
    classify: "Classify",
  },
  intents: {
    sales: "Sales",
    support: "Support",
    other: "Other",
  },
  stageTypes: {
    talk: "Talk",
    collect: "Collect",
    classify: "Classify",
    action: "Action",
    terminal: "Terminal",
  },
  convoStatus: {
    open: "Active",
    waiting_human: "Waiting for human",
    closed: "Closed",
  },
  restartPolicy: {
    ignore: "Ignore messages",
    restart: "Restart flow",
    fallback: "Fallback stage",
  },
  actions: {
    request_human: "Request human",
  },
  pagination: {
    showing: "Showing {from}–{to} of {total}",
    page: "{current} / {total}",
    perPage: "Per page",
    prev: "Previous",
    next: "Next",
  },
  channels: {
    statusConnected: "Connected",
    statusDisconnected: "Not connected",
    connectStepsTitle: "How to connect",
    stepConnect: "Click Connect WhatsApp",
    stepVerify: "Complete Meta Embedded Signup",
    stepLive: "Messages flow into Leads",
    allConnections: "All connections",
    whatsAppPrimary: "WhatsApp - primary channel",
    connectedSuccess: "WhatsApp connected successfully",
    instagramConnectedSuccess: "Instagram connected successfully",
    notConnectedHint: "Connect your business number to receive WhatsApp leads.",
    identity: "Account",
    actions: "Actions",
  },
  demo: {
    leadProfile: "Customer profile",
    simulateAs: "Simulate as customer",
    agentContext: "Agent context",
    openFullLead: "Open full lead",
    activeNow: "Active now",
    noLeadSelected: "Pick a customer from the list or start a new test chat",
    contactInfo: "Contact info",
    banner: "Simulator - you are the customer. Live WhatsApp is on Channels.",
  },
  errors: {
    badSecret: "Bad secret",
    createFailed: "Could not create",
    connectFailed: "Could not start connect",
    noAgent: "No agent. Seed the database.",
    noTenant: "No tenant. Seed the database.",
  },
};
