import type { UiCopy } from "./types";

export const en: UiCopy = {
  product: "Leady",
  nav: {
    home: "Home",
    setup: "Setup",
    chat: "Simulator",
    leads: "Leads",
    inbox: "Inbox",
    channels: "Channels",
    ops: "Ops",
    admin: "Admin",
  },
  langToggle: { he: "עברית", en: "English", uiLanguage: "UI language" },
  themeToggle: { appearance: "Appearance", system: "Match system", light: "Light", dark: "Dark" },
  actingAs: "Acting as {name}",
  stopActing: "Stop acting as tenant",
  page: {
    homeTitle: "Dashboard",
    homeBlurb: "Manage leads, conversations, and channels in one place.",
    homeSetup: "Finish Setup so the agent can greet with your intro.",
    homeChat: "Open simulator",
    setupTitle: "Business setup",
    setupBlurb: "Upload a knowledge file first — we extract setup fields, then you review business details.",
    chatTitle: "Agent simulator",
    chatBlurb: "You are messaging as the customer. Live WhatsApp is on Channels.",
    leadsTitle: "Leads",
    inboxTitle: "Inbox",
    channelsTitle: "Channels",
    opsTitle: "Ops",
    adminTitle: "Tenant admin",
  },
  home: {
    quickSetup: "Agent & knowledge setup",
    quickChat: "Customer simulation",
    quickLeads: "Lead list",
    quickInbox: "Tasks to approve",
    quickChannels: "Connect WhatsApp",
    tenantLabel: "Business",
    journeyTitle: "Your workflow",
    journeyBlurb: "Setup → Channels → Chat → Leads → Inbox",
    stepSetup: "Business & agent setup",
    stepChannels: "Connect WhatsApp",
    stepChat: "Test chat",
    stepLeads: "Manage leads",
    stepInbox: "Approve tasks",
    ctaInbox: "Review waiting tasks",
    ctaConnect: "Connect WhatsApp",
    whatsappOk: "WhatsApp connected",
    whatsappOff: "WhatsApp not connected",
  },
  common: {
    save: "Save",
    saving: "Saving…",
    next: "Next",
    back: "Back",
    extract: "Extract details",
    extracting: "Extracting…",
    empty: "—",
    pending: "pending",
    demo: "demo",
    delete: "Delete",
    confirmDeleteDemo: "Delete this demo lead and its conversation?",
    name: "Name",
    channel: "Channel",
    status: "Status",
    stage: "Stage",
    visit: "Visit",
    intent: "Intent",
    openLead: "Open lead",
    noLeads: "No leads yet. Start from the simulator.",
    nothingWaiting: "Nothing waiting.",
    comingSoon: "Coming soon",
    connectWhatsApp: "Connect WhatsApp",
    reconnectWhatsApp: "Reconnect",
    connectInstagram: "Connect Instagram",
    reconnectInstagram: "Reconnect",
    instagram: "Instagram",
    whatsapp: "WhatsApp",
    instagramProfile: "Instagram profile",
    zernioMissing: "Set ZERNIO_API_KEY in .env",
    connectedNumber: "Connected number",
    accountId: "Account id",
    createTenant: "Create tenant",
    tenantName: "Business name",
    tenantPhone: "Phone",
    openAsTenant: "Open as tenant",
    adminUnlock: "Enter the admin secret",
    adminSecret: "Secret",
    unlock: "Unlock",
    visitsWaiting: "Visits waiting for approval",
    captured: "Captured data",
    conversation: "Conversation",
    flow: "Flow",
    customers: "Customers",
    newChat: "New chat",
    knowledge: "Knowledge",
    business: "Business",
    done: "Done",
    stepOf: "Step {current} of {total}",
    enabled: "Enabled",
    disabled: "Disabled",
    on: "On",
    off: "Off",
    approve: "Approve",
    decline: "Decline",
    send: "Send",
    sending: "Sending…",
    need: "Need",
    phone: "Phone",
    email: "Email",
    version: "Version",
    menu: "Menu",
    search: "Search",
    all: "All",
    live: "Live",
    lastActive: "Last active",
    staff: "Staff",
    saveFailed: "Save failed",
    exportCsv: "Export CSV",
    anyStatus: "Any status",
    clearFilters: "Clear",
  },
  status: {
    new: "New",
    open: "Open",
    in_progress: "In progress",
    won: "Won",
    lost: "Lost",
  },
  roles: {
    lead: "Customer",
    agent: "Agent",
    human: "Human",
  },
  chat: {
    emptyThread: "No messages yet. Say hello as the customer.",
    placeholder: "Message as this customer",
    waitingHuman: "Waiting on a human…",
    pausedForHuman: "Paused for a human — continue in",
    startNew: "Start as a new customer or pick one from the list.",
    noIntro: "No intro yet",
    flowLabel: "Flow",
    languageLabel: "Agent language",
    sendFailed: "Send failed",
  },
  onboard: {
    agentLanguageLegend: "Agent language",
    agentLanguageHint: "Controls which language the agent replies in chat.",
    knowledgeHint:
      "Upload a .txt or .md file. We fill name, phone, intro, address, and hours so you can skip typing if they are already in the document.",
    knowledgePlaceholder: "Or paste notes here, then extract.",
    dropzoneIdle: "Drop a .txt / .md file here",
    dropzoneBusy: "Reading the file…",
    dropInvalid: "Drop .txt or .md files only",
    extractFailed: "Could not extract from the file",
    noLlm: "No LLM key configured — fill business details on the next step.",
    saveFailed: "Could not save",
    businessHint: "Review what we pulled from the file. Edit anything that is wrong or missing.",
    fieldName: "Business name",
    fieldPhone: "Public phone",
    fieldIntro: "Intro (what the agent should say it is)",
    fieldIntroPlaceholder: "We help local customers book a visit with the team.",
    fieldAddress: "Address (shown after a visit is requested)",
    fieldAddressPlaceholder: "Street, city",
    fieldHours: "Opening hours (included when asking for a time)",
    fieldHoursPlaceholder: "Sun–Thu 09:00–19:00",
    fieldBookingRequest: "Tentative booking message",
    fieldBookingApproved: "Approved booking message",
    fieldBookingRejected: "Declined booking message",
    templatesHint:
      "Leave empty for language defaults. Placeholders: {{slot}} {{address}} {{hours}} {{name}} {{phone}} {{email}} {{need}} {{kind}}",
    fieldIdleDays: "Reset conversation after idle days",
    idleHint:
      "The first customer message always gets this intro (no AI). After a conversation is done, or after this many days of silence, the next message gets the intro again. 0 = do not reset on idle.",
    doneHint: "The first message is always your intro. The next message is when the agent starts talking.",
    catalogLegend: "Flow type",
    collectLegend: "What to collect for a visit",
    collectHint:
      "The agent asks only the checked items. WhatsApp already has their number — leave Phone unchecked unless you also want a typed number.",
    filledFields: "Filled {count} business fields from the file.",
    insertToken: "Insert",
  },
  catalog: {
    inbox: {
      title: "Inbox (recommended)",
      blurb: "Greet, answer questions, then qualify and book when they want help.",
    },
    book: {
      title: "Booking",
      blurb: "Same conversation style, biased toward setting a meeting.",
    },
    faq: {
      title: "FAQ only",
      blurb: "Answer from your intro and files. No booking.",
    },
  },
  chatLanguage: {
    multi: {
      title: "Match customer",
      blurb: "Reply in Hebrew or English based on what they wrote.",
    },
    he: {
      title: "Hebrew only",
      blurb: "Always reply in Hebrew.",
    },
    en: {
      title: "English only",
      blurb: "Always reply in English.",
    },
  },
  bookingCollect: {
    time_preference: { title: "Preferred time", blurb: "Day and time for the visit" },
    name: { title: "Name", blurb: "Full name" },
    need: { title: "Need", blurb: "What to cover in the visit" },
    phone: { title: "Phone", blurb: "Callback number if different from chat" },
    email: { title: "Email", blurb: "For visit confirmation" },
    visit_kind: { title: "Visit kind", blurb: "Type of visit" },
  },
  inbox: {
    decisionLegend: "Decision",
    approveOption: "Approve",
    needInfoOption: "Need more info",
    notePlaceholder: "Note the agent should use",
    complete: "Complete and resume",
    bookingApproval: "Booking approval",
    tasksWaiting: "{count} tasks waiting",
    emptyHint: "When a customer requests a human or visit, the task appears here.",
    generalTask: "Human task",
    openChat: "Open simulator",
    reason: "Reason",
    reasons: {
      support_unresolved: "The agent could not resolve this and asked for a human.",
      escalation_requested: "The customer asked to speak with a person.",
    },
  },
  meeting: {
    approve: "Approve visit",
    decline: "Decline / suggest another time",
    visitDefault: "visit",
  },
  ops: {
    catalogLegend: "Catalog (re-clones the JSON flow)",
    afterDoneLegend: "After a conversation is done",
    ignoreMessages: "Ignore new messages",
    restartFlow: "Start the flow over",
    fallbackStage: "Switch to fallback stage",
    fallbackStageLabel: "Fallback stage",
    noneOption: "(none)",
    hitlLegend: "Human-in-the-loop",
    allowHuman: "Allow request_human",
    stagesLegend: "Stages allowed to escalate",
    intentsLegend: "Intents that may escalate",
    ownersNeverSee: "Business owners never see this page.",
  },
  flow: {
    start: "Start",
    afterDone: "After done",
    needFields: "Required fields",
    transitions: "Transitions",
    currentStage: "Current stage",
    progress: "Flow progress",
  },
  leadFields: {
    name: "Name",
    need: "Need",
    email: "Email",
    phone: "Phone",
    budget: "Budget",
    intent: "Intent",
    booking: "Booking",
    service: "Service",
    visit_kind: "Visit kind",
    time_preference: "Preferred time",
  },
  meetingKinds: { visit: "Visit", showroom: "Showroom", online: "Online", phone: "Phone call" },
  stages: {
    talk: "Conversation",
    escalate: "Escalate to human",
    done: "Done",
    waiting_human: "Waiting for human",
    collect: "Collect details",
    classify: "Classify",
  },
  intents: {
    sales: "Sales",
    support: "Support",
    other: "Other",
  },
  stageTypes: {
    talk: "Talk",
    collect: "Collect",
    classify: "Classify",
    action: "Action",
    terminal: "Terminal",
  },
  convoStatus: {
    open: "Active",
    waiting_human: "Waiting for human",
    closed: "Closed",
  },
  restartPolicy: {
    ignore: "Ignore messages",
    restart: "Restart flow",
    fallback: "Fallback stage",
  },
  actions: {
    request_human: "Request human",
  },
  pagination: {
    showing: "Showing {from}–{to} of {total}",
    page: "{current} / {total}",
    perPage: "Per page",
    prev: "Previous",
    next: "Next",
  },
  channels: {
    statusConnected: "Connected",
    statusDisconnected: "Not connected",
    connectStepsTitle: "How to connect",
    stepConnect: "Click Connect WhatsApp",
    stepVerify: "Complete Meta Embedded Signup",
    stepLive: "Messages flow into Leads",
    allConnections: "All connections",
    whatsAppPrimary: "WhatsApp — primary channel",
    connectedSuccess: "WhatsApp connected successfully",
    instagramConnectedSuccess: "Instagram connected successfully",
    notConnectedHint: "Connect your business number to receive WhatsApp leads.",
    identity: "Account",
    actions: "Actions",
  },
  demo: {
    leadProfile: "Customer profile",
    simulateAs: "Simulate as customer",
    agentContext: "Agent context",
    openFullLead: "Open full lead",
    activeNow: "Active now",
    noLeadSelected: "Pick a customer from the list or start a new test chat",
    contactInfo: "Contact info",
    banner: "Simulator — you are the customer. Live WhatsApp is on Channels.",
  },
  conversations: {
    title: "Conversations",
    blurb: "Every chat your agent is having, newest first. Open one to read it or take over.",
    today: "Today",
    yesterday: "Yesterday",
    noMessages: "No messages yet",
    rangeToday: "Today",
    range7d: "7 days",
    range30d: "30 days",
    rangeAll: "All",
    dayCount: "{count} conversations",
    dayCountOne: "1 conversation",
    typeFilter: "Type",
    pulseTotal: "In view",
    pulseNeedsYou: "Waiting on you",
    pulseVisits: "Visits to approve",
    pulseBooked: "Visits approved",
    pausedForYou: "Paused for you",
    visitPending: "Visit to approve",
    openedOn: "First message {date}",
    emptyTitle: "No conversations in this range",
    emptyBody: "Widen the dates, or clear the filters to see everything.",
    emptyAction: "Show all conversations",
    openConversation: "Open conversation with {name}",
  },
  takeover: {
    legend: "Who answers",
    botOn: "Agent is answering",
    botOff: "You are answering",
    pause: "Take over",
    resume: "Hand back to the agent",
    replyPlaceholder: "Reply to the customer as yourself",
    replyHint: "Goes straight to the customer on their channel. The agent stays quiet while you are in control.",
    failed: "Could not send",
    noConversation: "No conversation yet for this customer.",
    switching: "Switching…",
  },
  metrics: {
    legend: "Last 7 days",
    leadsToday: "New leads today",
    leads7d: "New leads this week",
    activeConversations: "Active conversations",
    waitingHuman: "Paused for you",
    openTasks: "Tasks to approve",
    meetingsPending: "Visits awaiting approval",
    meetingsApproved7d: "Visits approved this week",
    messages7d: "Messages in / out",
    autoHandled: "Handled without you",
    autoHandledHint: "Share of the last 30 days' conversations the agent closed without asking for a human.",
    noData: "Not enough conversations yet",
    needsYou: "Needs you now",
    allClear: "Nothing is waiting on you.",
  },
  errors: {
    badSecret: "Bad secret",
    createFailed: "Could not create",
    connectFailed: "Could not start connect",
    noAgent: "No agent. Seed the database.",
    noTenant: "No tenant. Seed the database.",
  },
};
