import type { UiCopy } from "./types";

export const he: UiCopy = {
  product: "לידי",
  nav: {
    home: "בית",
    setup: "הגדרה",
    chat: "צ׳אט",
    leads: "לידים",
    inbox: "תיבת נכנסות",
    channels: "ערוצים",
    ops: "תפעול",
    admin: "אדמין",
  },
  langToggle: { he: "עברית", en: "English" },
  actingAs: (name) => `מחובר כ־${name}`,
  stopActing: "חזרה לאדמין",
  page: {
    homeTitle: "לידי",
    homeBlurb:
      "צ׳אט הדגמה ללקוח, לידים עם שדות שנקלטו, וואטסאפ דרך זרניו. תצוגת הצ׳אט עובדת בלי לשלוח לוואטסאפ.",
    homeSetup: "השלימו את ההגדרה כדי שהסוכן יברך עם המבוא שלכם.",
    homeChat: "פתיחת תצוגת צ׳אט",
    setupTitle: "הגדרה",
    setupBlurb: "העלו קובץ ידע — נחלץ ממנו פרטים, ואז תבדקו את פרטי העסק.",
    chatTitle: "תצוגת צ׳אט",
    leadsTitle: "לידים",
    inboxTitle: "תיבת נכנסות",
    channelsTitle: "ערוצים",
    opsTitle: "תפעול",
    adminTitle: "אדמין",
  },
  common: {
    save: "שמירה",
    saving: "שומר…",
    next: "הבא",
    back: "חזרה",
    extract: "חלץ פרטים",
    extracting: "מחלץ…",
    empty: "—",
    pending: "ממתין",
    demo: "דמו",
    delete: "מחיקה",
    confirmDeleteDemo: "למחוק את ליד הדמו ואת השיחה שלו?",
    name: "שם",
    channel: "ערוץ",
    status: "סטטוס",
    stage: "שלב",
    visit: "ביקור",
    intent: "כוונה",
    openLead: "פתח ליד",
    noLeads: "אין לידים עדיין. נסו תצוגת צ׳אט.",
    nothingWaiting: "אין משימות ממתינות.",
    comingSoon: "בקרוב",
    connectWhatsApp: "חיבור וואטסאפ",
    reconnectWhatsApp: "חיבור מחדש",
    instagram: "אינסטגרם",
    whatsapp: "וואטסאפ",
    zernioMissing: "חסר מפתח זרניו ב־.env",
    connectedNumber: "מספר מחובר",
    accountId: "מזהה חשבון",
    createTenant: "יצירת דייר",
    tenantName: "שם העסק",
    tenantPhone: "טלפון",
    openAsTenant: "התחבר כדייר",
    adminUnlock: "הזינו את סוד האדמין",
    adminSecret: "סוד",
    unlock: "כניסה",
    visitsWaiting: "ביקורים שממתינים לאישור",
    captured: "נתונים שנקלטו",
    conversation: "שיחה",
    flow: "זרימה",
    customers: "לקוחות",
    newChat: "צ׳אט חדש",
    knowledge: "ידע",
    business: "עסק",
    done: "סיום",
    step: (n, total) => `שלב ${n} מתוך ${total}`,
  },
  status: {
    new: "חדש",
    open: "פתוח",
    in_progress: "בטיפול",
    won: "נסגר בהצלחה",
    lost: "אבד",
  },
};
