import type { UiCopy } from "./types";

export const he: UiCopy = {
  product: "לידי",
  nav: {
    home: "בית",
    setup: "הגדרה",
    chat: "בדיקת סוכן",
    leads: "לידים",
    inbox: "תיבת נכנסות",
    channels: "ערוצים",
    ops: "תפעול",
    admin: "אדמין",
  },
  langToggle: { he: "עברית", en: "English", uiLanguage: "שפת ממשק" },
  themeToggle: { appearance: "מראה", system: "לפי המערכת", light: "בהיר", dark: "כהה" },
  actingAs: "מחובר כ־{name}",
  stopActing: "חזרה לאדמין",
  page: {
    homeTitle: "לוח בקרה",
    homeBlurb: "ניהול לידים, שיחות וערוצים — הכל במקום אחד.",
    homeSetup: "השלימו את ההגדרה כדי שהסוכן יברך עם המבוא שלכם.",
    homeChat: "פתיחת סימולטור",
    setupTitle: "הגדרת העסק",
    setupBlurb: "העלו קובץ ידע — נחלץ ממנו פרטים, ואז תבדקו את פרטי העסק.",
    chatTitle: "סימולטור סוכן",
    chatBlurb: "אתם כותבים כלקוח. וואטסאפ חי נמצא בערוצים.",
    leadsTitle: "לידים",
    inboxTitle: "תיבת נכנסות",
    channelsTitle: "ערוצים",
    opsTitle: "תפעול",
    adminTitle: "ניהול דיירים",
  },
  home: {
    quickSetup: "הגדרת סוכן וידע",
    quickChat: "סימולציית לקוח",
    quickLeads: "רשימת לידים",
    quickInbox: "משימות לאישור",
    quickChannels: "חיבור וואטסאפ",
    tenantLabel: "עסק",
    journeyTitle: "מסלול העבודה",
    journeyBlurb: "הגדרה → ערוצים → שיחות → לידים → תיבת נכנסות",
    stepSetup: "הגדרת העסק והסוכן",
    stepChannels: "חיבור וואטסאפ",
    stepChat: "בדיקת צ׳אט",
    stepLeads: "ניהול לידים",
    stepInbox: "אישור משימות",
    ctaInbox: "טיפול במשימות ממתינות",
    ctaConnect: "חיבור וואטסאפ",
    whatsappOk: "וואטסאפ מחובר",
    whatsappOff: "וואטסאפ לא מחובר",
  },
  common: {
    save: "שמירה",
    saving: "שומר…",
    next: "הבא",
    back: "חזרה",
    extract: "חילוץ פרטים",
    extracting: "מחלץ…",
    empty: "—",
    pending: "ממתין",
    demo: "דמו",
    delete: "מחיקה",
    confirmDeleteDemo: "למחוק את ליד הדמו ואת השיחה שלו?",
    name: "שם",
    channel: "ערוץ",
    status: "סטטוס",
    stage: "שלב",
    visit: "ביקור",
    intent: "כוונה",
    openLead: "פתיחת ליד",
    noLeads: "אין לידים עדיין. התחילו מהסימולטור.",
    nothingWaiting: "אין משימות ממתינות.",
    comingSoon: "בקרוב",
    connectWhatsApp: "חיבור וואטסאפ",
    reconnectWhatsApp: "חיבור מחדש",
    connectInstagram: "חיבור אינסטגרם",
    reconnectInstagram: "חיבור מחדש",
    instagram: "אינסטגרם",
    whatsapp: "וואטסאפ",
    instagramProfile: "פרופיל אינסטגרם",
    zernioMissing: "חסר מפתח ZERNIO_API_KEY בקובץ .env",
    connectedNumber: "מספר מחובר",
    accountId: "מזהה חשבון",
    createTenant: "יצירת דייר",
    tenantName: "שם העסק",
    tenantPhone: "טלפון",
    openAsTenant: "התחבר כדייר",
    adminUnlock: "הזינו את סוד האדמין",
    adminSecret: "סוד",
    unlock: "כניסה",
    visitsWaiting: "ביקורים שממתינים לאישור",
    captured: "נתונים שנקלטו",
    conversation: "שיחה",
    flow: "זרימה",
    customers: "לקוחות",
    newChat: "צ׳אט חדש",
    knowledge: "ידע",
    business: "פרטי עסק",
    done: "סיום",
    stepOf: "שלב {current} מתוך {total}",
    enabled: "פעיל",
    disabled: "כבוי",
    on: "פעיל",
    off: "כבוי",
    approve: "אישור",
    decline: "דחייה",
    send: "שליחה",
    sending: "שולח…",
    need: "צורך",
    phone: "טלפון",
    email: "אימייל",
    version: "גרסה",
    menu: "תפריט",
    search: "חיפוש",
    all: "הכל",
    live: "חי",
    lastActive: "פעילות אחרונה",
    staff: "צוות",
    saveFailed: "השמירה נכשלה",
    exportCsv: "ייצוא CSV",
    anyStatus: "כל הסטטוסים",
    clearFilters: "ניקוי",
  },
  status: {
    new: "חדש",
    open: "פתוח",
    in_progress: "בטיפול",
    won: "נסגר בהצלחה",
    lost: "אבד",
  },
  roles: {
    lead: "לקוח",
    agent: "סוכן",
    human: "נציג",
  },
  chat: {
    emptyThread: "אין הודעות עדיין. כתבו שלום כלקוח.",
    placeholder: "הודעה בתור הלקוח",
    waitingHuman: "ממתין לנציג…",
    pausedForHuman: "השיחה מושהית — המשיכו ב",
    startNew: "התחילו כלקוח חדש או בחרו מהרשימה.",
    noIntro: "אין מבוא עדיין",
    flowLabel: "זרימה",
    languageLabel: "שפת סוכן",
    sendFailed: "השליחה נכשלה",
  },
  onboard: {
    agentLanguageLegend: "שפת הסוכן",
    agentLanguageHint: "קובע באיזו שפה הסוכן עונה בצ׳אט.",
    knowledgeHint:
      "העלו קובץ .txt או .md. נמלא שם, טלפון, מבוא, כתובת ושעות — כדי שלא תצטרכו להקליד אם הם כבר במסמך.",
    knowledgePlaceholder: "או הדביקו טקסט כאן ולחצו חילוץ.",
    dropzoneIdle: "גררו קובץ .txt / .md לכאן",
    dropzoneBusy: "קורא את הקובץ…",
    dropInvalid: "רק קבצי .txt או .md",
    extractFailed: "לא הצלחנו לחלץ מהקובץ",
    noLlm: "אין מפתח LLM — מלאו ידנית בשלב הבא.",
    saveFailed: "השמירה נכשלה",
    businessHint: "בדקו מה שחולץ מהקובץ. תקנו מה שחסר או שגוי.",
    fieldName: "שם העסק",
    fieldPhone: "טלפון ציבורי",
    fieldIntro: "מבוא (מה הסוכן אומר על עצמו)",
    fieldIntroPlaceholder: "שמחים לעזור לכם לתאם ביקור עם הצוות.",
    fieldAddress: "כתובת (מוצגת אחרי בקשת ביקור)",
    fieldAddressPlaceholder: "רחוב, עיר",
    fieldHours: "שעות פתיחה (בשאלה על מועד)",
    fieldHoursPlaceholder: "א׳–ה׳ 09:00–19:00",
    fieldBookingRequest: "הודעת בקשת ביקור (טנטטיבית)",
    fieldBookingApproved: "הודעת ביקור מאושר",
    fieldBookingRejected: "הודעת ביקור נדחה",
    templatesHint:
      "השאירו ריק לברירת מחדל לפי שפה. מציינים: {{slot}} {{address}} {{hours}} {{name}} {{phone}} {{email}} {{need}} {{kind}}",
    fieldIdleDays: "איפוס שיחה אחרי ימי שקט",
    idleHint:
      "ההודעה הראשונה תמיד מקבלת את המבוא (ללא AI). אחרי סיום שיחה, או אחרי כמה ימים ללא פעילות, ההודעה הבאה שוב תקבל מבוא. 0 = ללא איפוס.",
    doneHint: "ההודעה הראשונה תמיד המבוא שלכם. מההודעה השנייה הסוכן מתחיל לדבר.",
    catalogLegend: "סוג זרימה",
    collectLegend: "מה לאסוף לפני ביקור",
    collectHint:
      "הסוכן שואל רק מה שסימנתם. בוואטסאפ כבר יש מספר — השאירו טלפון לא מסומן אלא אם אתם רוצים מספר מוקלד.",
    filledFields: "מילאנו {count} שדות עסק מהקובץ.",
    insertToken: "הוספה",
  },
  catalog: {
    inbox: {
      title: "תיבה (מומלץ)",
      blurb: "ברכה, מענה על שאלות, ואז איסוף פרטים ותיאום ביקור.",
    },
    book: {
      title: "תיאום ביקורים",
      blurb: "אותו סגנון שיחה, עם דגש על קביעת פגישה.",
    },
    faq: {
      title: "שאלות ותשובות בלבד",
      blurb: "מענה מהמבוא והקבצים — בלי תיאום ביקורים.",
    },
  },
  chatLanguage: {
    multi: {
      title: "לפי הלקוח",
      blurb: "עונה בעברית או באנגלית לפי מה שכתבו.",
    },
    he: {
      title: "עברית בלבד",
      blurb: "הסוכן תמיד עונה בעברית.",
    },
    en: {
      title: "English only",
      blurb: "הסוכן תמיד עונה באנגלית.",
    },
  },
  bookingCollect: {
    time_preference: { title: "מועד מועדף", blurb: "יום ושעה לביקור" },
    name: { title: "שם", blurb: "שם מלא" },
    need: { title: "צורך", blurb: "מה חשוב לכסות בפגישה" },
    phone: { title: "טלפון", blurb: "מספר לחזרה (אם שונה מהצ׳אט)" },
    email: { title: "אימייל", blurb: "לאישור הביקור" },
    visit_kind: { title: "סוג ביקור", blurb: "סוג הפגישה" },
  },
  inbox: {
    decisionLegend: "החלטה",
    approveOption: "אישור",
    needInfoOption: "צריך עוד פרטים",
    notePlaceholder: "הערה שהסוכן ישתמש בה",
    complete: "סיום והמשך",
    bookingApproval: "אישור ביקור",
    tasksWaiting: "{count} משימות ממתינות",
    emptyHint: "כשלקוח מבקש נציג או ביקור — המשימה תופיע כאן.",
    generalTask: "משימת נציג",
    openChat: "פתיחת סימולטור",
    reason: "סיבה",
    reasons: {
      support_unresolved: "הסוכן לא הצליח לפתור וביקש נציג.",
      escalation_requested: "הלקוח ביקש לדבר עם נציג אנושי.",
    },
  },
  meeting: {
    approve: "אישור הביקור",
    decline: "דחייה / הצעת מועד אחר",
    visitDefault: "ביקור",
  },
  ops: {
    catalogLegend: "קטלוג (משכפל את הזרימה)",
    afterDoneLegend: "אחרי סיום שיחה",
    ignoreMessages: "התעלם מהודעות חדשות",
    restartFlow: "התחל את הזרימה מחדש",
    fallbackStage: "עבור לשלב גיבוי",
    fallbackStageLabel: "שלב גיבוי",
    noneOption: "(ללא)",
    hitlLegend: "מעורבות אנושית",
    allowHuman: "אפשר העברה לנציג",
    stagesLegend: "שלבים שמותר להעביר מהם",
    intentsLegend: "כוונות שמותר להעביר",
    ownersNeverSee: "בעלי העסק לא רואים דף זה.",
  },
  flow: {
    start: "התחלה",
    afterDone: "אחרי סיום",
    needFields: "שדות נדרשים",
    transitions: "מעברים",
    currentStage: "שלב נוכחי",
    progress: "התקדמות בזרימה",
  },
  leadFields: {
    name: "שם",
    need: "צורך",
    email: "אימייל",
    phone: "טלפון",
    budget: "תקציב",
    intent: "כוונה",
    booking: "הזמנה",
    service: "שירות",
    visit_kind: "סוג ביקור",
    time_preference: "מועד מועדף",
  },
  meetingKinds: { visit: "ביקור", showroom: "אולם תצוגה", online: "מקוון", phone: "שיחת טלפון" },
  stages: {
    talk: "שיחה",
    escalate: "העברה לנציג",
    done: "סיום",
    waiting_human: "ממתין לנציג",
    collect: "איסוף פרטים",
    classify: "סיווג",
  },
  intents: {
    sales: "מכירות",
    support: "תמיכה",
    other: "אחר",
  },
  stageTypes: {
    talk: "שיחה",
    collect: "איסוף",
    classify: "סיווג",
    action: "פעולה",
    terminal: "סיום",
  },
  convoStatus: {
    open: "פעיל",
    waiting_human: "ממתין לנציג",
    closed: "סגור",
  },
  restartPolicy: {
    ignore: "התעלם מהודעות",
    restart: "התחל מחדש",
    fallback: "שלב גיבוי",
  },
  actions: {
    request_human: "בקשת נציג",
  },
  pagination: {
    showing: "מציג {from}–{to} מתוך {total}",
    page: "{current} / {total}",
    perPage: "לעמוד",
    prev: "הקודם",
    next: "הבא",
  },
  channels: {
    statusConnected: "מחובר",
    statusDisconnected: "לא מחובר",
    connectStepsTitle: "איך מתחברים",
    stepConnect: "לחצו חיבור וואטסאפ",
    stepVerify: "אשרו ב-Meta Embedded Signup",
    stepLive: "הודעות יגיעו ללידים",
    allConnections: "כל החיבורים",
    whatsAppPrimary: "וואטסאפ — ערוץ ראשי",
    connectedSuccess: "וואטסאפ מחובר בהצלחה",
    instagramConnectedSuccess: "אינסטגרם מחובר בהצלחה",
    notConnectedHint: "חברו את מספר העסק כדי לקבל לידים מוואטסאפ.",
    identity: "חשבון",
    actions: "פעולות",
  },
  demo: {
    leadProfile: "פרטי לקוח",
    simulateAs: "סימולציה כלקוח",
    agentContext: "הקשר הסוכן",
    openFullLead: "פתיחת ליד מלא",
    activeNow: "פעיל עכשיו",
    noLeadSelected: "בחרו לקוח מהרשימה או התחילו בדיקה חדשה",
    contactInfo: "פרטי קשר",
    banner: "סימולטור — אתם הלקוח. וואטסאפ חי נמצא בערוצים.",
  },
  conversations: {
    title: "שיחות",
    blurb: "כל השיחות שהסוכן מנהל, מהחדשה לישנה. היכנסו לשיחה כדי לקרוא או להשתלט.",
    today: "היום",
    yesterday: "אתמול",
    noMessages: "עדיין אין הודעות",
    rangeToday: "היום",
    range7d: "7 ימים",
    range30d: "30 ימים",
    rangeAll: "הכל",
    dayCount: "{count} שיחות",
    dayCountOne: "שיחה אחת",
    typeFilter: "סוג",
    pulseTotal: "בתצוגה",
    pulseNeedsYou: "ממתין לכם",
    pulseVisits: "ביקורים לאישור",
    pulseBooked: "ביקורים שאושרו",
    pausedForYou: "ממתין לכם",
    visitPending: "ביקור לאישור",
    openedOn: "הודעה ראשונה {date}",
    emptyTitle: "אין שיחות בטווח הזה",
    emptyBody: "הרחיבו את הטווח או נקו את הסינון כדי לראות הכל.",
    emptyAction: "הצגת כל השיחות",
    openConversation: "פתיחת השיחה עם {name}",
    loading: "טוען שיחות",
  },
  takeover: {
    legend: "מי עונה",
    botOn: "הסוכן עונה",
    botOff: "אתם עונים",
    pause: "השתלטות על השיחה",
    resume: "החזרה לסוכן",
    replyPlaceholder: "השיבו ללקוח בשמכם",
    replyHint: "נשלח ישירות ללקוח בערוץ שלו. הסוכן שותק כל עוד אתם מנהלים את השיחה.",
    failed: "השליחה נכשלה",
    noConversation: "אין עדיין שיחה עם הלקוח הזה.",
    switching: "מחליף…",
  },
  metrics: {
    legend: "שבעת הימים האחרונים",
    leadsToday: "לידים חדשים היום",
    leads7d: "לידים חדשים השבוע",
    activeConversations: "שיחות פעילות",
    waitingHuman: "ממתין לכם",
    openTasks: "משימות לאישור",
    meetingsPending: "ביקורים ממתינים לאישור",
    meetingsApproved7d: "ביקורים שאושרו השבוע",
    messages7d: "הודעות נכנסות / יוצאות",
    autoHandled: "טופל בלעדיכם",
    autoHandledHint: "אחוז השיחות מ-30 הימים האחרונים שהסוכן סגר בלי לבקש אדם.",
    noData: "עדיין אין מספיק שיחות",
    needsYou: "דורש טיפול עכשיו",
    allClear: "שום דבר לא ממתין לכם.",
  },
  errors: {
    badSecret: "סוד שגוי",
    createFailed: "יצירה נכשלה",
    connectFailed: "החיבור נכשל",
    noAgent: "אין סוכן. הריצו seed לבסיס הנתונים.",
    noTenant: "אין דייר. הריצו seed לבסיס הנתונים.",
  },
};
