import type { UiCopy } from "./types";

export const he: UiCopy = {
  product: "לידי",
  nav: {
    home: "בית",
    setup: "הגדרה",
    chat: "בדיקת סוכן",
    leads: "פניות",
    inbox: "משימות",
    channels: "ערוצים",
    ops: "תפעול",
    admin: "אדמין",
    team: "צוות",
    digest: "תקציר יומי",
  },
  langToggle: { he: "עברית", en: "English", uiLanguage: "שפת ממשק" },
  themeToggle: { appearance: "מראה", system: "לפי המערכת", light: "בהיר", dark: "כהה" },
  actingAs: "מחובר כ־{name}",
  stopActing: "חזרה לאדמין",
  page: {
    homeTitle: "לוח בקרה",
    homeBlurb: "ניהול לידים, שיחות וערוצים - הכל במקום אחד.",
    homeSetup: "השלימו את ההגדרה כדי שהסוכן יברך עם המבוא שלכם.",
    homeChat: "פתיחת סימולטור",
    setupTitle: "הגדרת העסק",
    setupBlurb: "העלו קובץ ידע - נחלץ ממנו פרטים, ואז תבדקו את פרטי העסק.",
    chatTitle: "סימולטור סוכן",
    chatBlurb: "אתם כותבים כלקוח. וואטסאפ חי נמצא בערוצים.",
    leadsTitle: "פניות",
    inboxTitle: "משימות",
    channelsTitle: "ערוצים",
    opsTitle: "תפעול",
    adminTitle: "ניהול דיירים",
    teamTitle: "צוות",
    teamBlurb: "הזמינו עמיתים ונהלו תפקידים לעסק זה.",
    signInTitle: "התחברות",
    signInBlurb: "התחברו כדי לנהל את תיבת העסק שלכם.",
    clerkMissing:
      "Clerk לא מוגדר. יש להגדיר NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ו־CLERK_SECRET_KEY, או להפעיל DEV_AUTH_BYPASS לשימוש מקומי.",
    noAccessTitle: "אין גישה",
    noAccessBlurb: "אתם מחוברים, אבל עדיין לא שויכתם לאף עסק במערכת.",
    noAccessHint: "בקשו מבעל העסק לשלוח לכם הזמנה, ואז פתחו את הקישור מהמייל.",
    activating: "מחברים אתכם…",
    alreadySignedInTitle: "כבר מחוברים",
    alreadySignedInBlurb: "התנתקו כדי להתחבר עם חשבון אחר.",
    switchAccountHint: "התנתקו, ואז התחברו עם אימייל אחר.",
  },
  home: {
    quickSetup: "הגדרת סוכן וידע",
    quickChat: "סימולציית לקוח",
    quickLeads: "רשימת פניות",
    quickInbox: "משימות לאישור",
    quickChannels: "חיבור וואטסאפ",
    tenantLabel: "עסק",
    journeyTitle: "מסלול העבודה",
    journeyBlurb: "הגדרה → ערוצים → שיחות → פניות → משימות",
    stepSetup: "הגדרת העסק והסוכן",
    stepChannels: "חיבור וואטסאפ",
    stepChat: "בדיקת צ׳אט",
    stepLeads: "ניהול פניות",
    stepInbox: "אישור משימות",
    ctaInbox: "טיפול במשימות ממתינות",
    ctaConnect: "חיבור וואטסאפ",
    whatsappOk: "וואטסאפ מחובר",
    whatsappOff: "וואטסאפ לא מחובר",
  },
  common: {
    save: "שמירה",
    saving: "שומר…",
    next: "הבא",
    back: "חזרה",
    extract: "חילוץ פרטים",
    extracting: "מחלץ…",
    empty: "-",
    pending: "ממתין",
    demo: "דמו",
    delete: "מחיקה",
    confirmDeleteDemo: "למחוק את ליד הדמו ואת השיחה שלו?",
    showDemoLeads: "הצג משתמשי דמו",
    name: "שם",
    channel: "ערוץ",
    status: "סטטוס",
    stage: "שלב",
    visit: "ביקור",
    intent: "כוונה",
    openLead: "פתיחת ליד",
    noLeads: "אין לקוחות עדיין. התחילו מהסימולטור.",
    nothingWaiting: "אין משימות ממתינות.",
    comingSoon: "בקרוב",
    connectWhatsApp: "חיבור וואטסאפ",
    reconnectWhatsApp: "חיבור מחדש",
    connectInstagram: "חיבור אינסטגרם",
    reconnectInstagram: "חיבור מחדש",
    instagram: "אינסטגרם",
    whatsapp: "וואטסאפ",
    instagramProfile: "פרופיל אינסטגרם",
    zernioMissing: "חסר מפתח ZERNIO_API_KEY בקובץ .env",
    connectedNumber: "מספר מחובר",
    accountId: "מזהה חשבון",
    createTenant: "יצירת דייר",
    tenantName: "שם העסק",
    tenantPhone: "טלפון",
    ownerEmail: "אימייל בעלים",
    openAsTenant: "התחבר כדייר",
    account: "חשבון",
    signOut: "התנתקות",
    backToSignIn: "חזרה להתחברות",
    visitsWaiting: "ביקורים שממתינים לאישור",
    captured: "נתונים שנקלטו",
    conversation: "שיחה",
    flow: "סגנון שיחה",
    advanced: "מתקדם",
    customers: "לקוחות",
    newChat: "צ׳אט חדש",
    knowledge: "ידע",
    business: "פרטי עסק",
    done: "סיום",
    editDetails: "עריכת פרטים",
    visitsTab: "ביקורים",
    decisionsTab: "החלטות",
    meetingsTab: "בקשות",
    noVisits: "אין ביקורים עדיין.",
    noDecisions: "אין החלטות ממתינות.",
    noMeetings: "אין בקשות עדיין.",
    details: "פרטים",
    close: "סגור",
    cancel: "ביטול",
    stepOf: "שלב {current} מתוך {total}",
    enabled: "פעיל",
    disabled: "כבוי",
    on: "פעיל",
    off: "כבוי",
    approve: "אישור",
    decline: "דחייה",
    send: "שליחה",
    sending: "שולח…",
    need: "פרטי הפגישה",
    phone: "טלפון",
    email: "אימייל",
    version: "גרסה",
    menu: "תפריט",
    search: "חיפוש",
    all: "הכל",
    live: "חי",
    lastActive: "פעילות אחרונה",
    staff: "צוות",
    saveFailed: "השמירה נכשלה",
  },
  status: {
    new: "חדש",
    open: "פתוח",
    in_progress: "בטיפול",
    won: "נסגר בהצלחה",
    lost: "אבד",
  },
  roles: {
    lead: "לקוח",
    agent: "סוכן",
    human: "נציג",
  },
  chat: {
    emptyThread: "אין הודעות עדיין. כתבו שלום כלקוח.",
    placeholder: "הודעה בתור הלקוח",
    waitingHuman: "ממתין לנציג…",
    pausedForHuman: "השיחה מושהית - המשיכו ב",
    startNew: "התחילו כלקוח חדש או בחרו מהרשימה.",
    noIntro: "אין מבוא עדיין",
    flowLabel: "סגנון שיחה",
    languageLabel: "שפת סוכן",
    sendFailed: "השליחה נכשלה",
    today: "היום",
    yesterday: "אתמול",
  },
  onboard: {
    agentLanguageLegend: "שפת הסוכן",
    agentLanguageHint: "קובע באיזו שפה הסוכן עונה בצ׳אט.",
    knowledgeHint:
      "העלו קובץ .txt או .md. נמלא שם, טלפון, מבוא, כתובת ושעות - כדי שלא תצטרכו להקליד אם הם כבר במסמך.",
    knowledgePlaceholder: "או הדביקו טקסט כאן ולחצו חילוץ.",
    dropzoneIdle: "גררו קובץ .txt / .md לכאן",
    dropzoneBusy: "קורא את הקובץ…",
    dropInvalid: "רק קבצי .txt או .md",
    extractFailed: "לא הצלחנו לחלץ מהקובץ",
    noLlm: "אין מפתח LLM - מלאו ידנית בשלב הבא.",
    saveFailed: "השמירה נכשלה",
    businessHint: "",
    fieldName: "שם העסק",
    fieldPhone: "טלפון ציבורי",
    fieldIntro: "הצגה עצמית (מה הסוכן אומר בתחילת שיחה)",
    fieldIntroPlaceholder: "שמחים לעזור לכם לתאם ביקור עם הצוות.",
    fieldAddress: "כתובת (מוצגת אחרי בקשת ביקור)",
    fieldAddressPlaceholder: "רחוב, עיר",
    fieldHours: "שעות פתיחה (בשאלה על מועד)",
    fieldHoursPlaceholder: "א׳–ה׳ 09:00–19:00",
    fieldBookingRequest: "הודעת בקשת ביקור (טנטטיבית)",
    fieldBookingApproved: "הודעת ביקור מאושר",
    fieldBookingRejected: "הודעת ביקור נדחה",
    templatesHint:
      "השאירו ריק לברירת מחדל לפי שפה. מציינים: {{date}} {{time}} {{slot}} {{name}} {{phone}} {{details}} {{need}} {{kind}} {{address}} {{hours}} {{email}}",
    fieldIdleDays: "איפוס שיחה אחרי ימי שקט",
    idleHint:
      "ההודעה הראשונה תמיד מקבלת את המבוא (ללא AI). אחרי תקופת שקט ארוכה הסוכן יכול לשאול אם לפתוח שיחה חדשה — בלי לסובב אוטומטית. 0 = לא להתייחס לשקט כרמז.",
    doneHint: "ההודעה הראשונה תמיד המבוא שלכם. מההודעה השנייה הסוכן מתחיל לדבר.",
    catalogLegend: "מצב הסוכן",
    capabilitiesLegend: "יכולות",
    capabilitiesHint: "מה הסוכן יכול לעשות. בלי יכולות — רק מענה מהידע.",
    bookingStanceLegend: "סגנון תיאום",
    collectLegend: "מה לאסוף לפני ביקור",
    collectHint:
      "הסוכן שואל רק מה שסימנתם. שם ומועד תמיד נאספים. בוואטסאפ כבר יש מספר - השאירו טלפון לא מסומן אלא אם אתם רוצים מספר מוקלד.",
    timeAlwaysCollected: "תמיד נאסף (חובה).",
    reservationCollectLegend: "מה לאסוף להזמנת אירוח",
    reservationCollectHint:
      "כניסה ויציאה תמיד נאספים. סמנו שדות מוכנים או הוסיפו מפתח מותאם (למשל dogs, parking).",
    reservationDatesAlways: "כניסה · יציאה: תמיד נאספים.",
    reservationCustomField: "מפתח שדה מותאם",
    reservationCustomFieldHint: "אותיות קטנות_עם_קווים",
    reservationAddField: "הוסף שדה",
    reservationSubmitModeLegend: "איך לסיים בקשת אירוח",
    reservationSubmitModeHitl: "נציג מאשר כל בקשה",
    reservationSubmitModeHitlBlurb:
      "הסוכן אוסף פרטים ויוצר בקשה ממתינה בתיבת הנכנסות.",
    reservationSubmitModeLink: "שליחת קישור להזמנה (עצמי)",
    reservationSubmitModeLinkBlurb:
      "הסוכן אוסף פרטים ושולח קישור להשלמת ההזמנה באתר. בלי אישור בתיבה.",
    reservationBookingLinkLegend: "תבנית קישור להזמנה",
    reservationBookingLinkHint:
      "חובה לכלול {{checkIn}} ו־{{checkOut}}. אופציונלי: {{guests}} {{unit}} {{name}} {{phone}} {{email}} {{propertySlug}}.",
    reservationBookingLinkInvalid:
      "מצב קישור דורש תבנית URL שכוללת {{checkIn}} ו־{{checkOut}}.",
    reservationSendLinkTemplateLegend: "הודעה בשליחת הקישור (אופציונלי)",
    reservationSendLinkTemplateHint:
      "השאירו ריק לברירת המחדל. השתמשו ב־{{bookingUrl}} ובאותם אסימוני תאריך.",
    filledFields: "מילאנו {count} שדות עסק מהקובץ.",
    insertToken: "הוספה",
  },
  catalog: {
    inbox: {
      title: "סיוע",
      blurb: "מענה לשאלות; היכולות למטה קובעות תיאום ועוד.",
    },
    faq: {
      title: "שאלות ותשובות בלבד",
      blurb: "מענה מהמבוא והקבצים — בלי יכולות עסקיות.",
    },
  },
  capabilities: {
    booking: {
      title: "תיאום פגישות",
      blurb: "איסוף פרטי ביקור ושליחת בקשת פגישה לאישור.",
    },
    reservations: {
      title: "הזמנת אירוח",
      blurb: "לילות אירוח עם בדיקת זמינות מקישור מותאם ואישור בעלים.",
    },
  },
  bookingStance: {
    passive: {
      title: "כשמבקשים",
      blurb: "קודם מענה; תיאום רק אחרי בקשה מפורשת לקבוע.",
    },
    proactive: {
      title: "עידוד לתיאום",
      blurb: "אחרי עזרה, מזמינים בעדינות לקבוע כשמתאים.",
    },
  },
  chatLanguage: {
    multi: {
      title: "לפי הלקוח",
      blurb: "עונה בעברית או באנגלית לפי מה שכתבו.",
    },
    he: {
      title: "עברית בלבד",
      blurb: "תמיד עונה בעברית, גם אם הלקוח כותב באנגלית.",
    },
    en: {
      title: "English only",
      blurb: "הסוכן תמיד עונה באנגלית.",
    },
  },
  bookingCollect: {
    time_preference: { title: "מועד מועדף", blurb: "יום ושעה לביקור" },
    name: { title: "שם", blurb: "שם מלא" },
    need: { title: "פרטי הפגישה", blurb: "מה לרשום על מטרת/תוכן הפגישה" },
    phone: {
      title: "טלפון",
      blurb: "שואלים כשחסר; מאשרים כשאפשר לדעת את מספר הצ'אט (וואטסאפ).",
    },
    email: { title: "אימייל", blurb: "לאישור הביקור" },
    visit_kind: { title: "סוג ביקור", blurb: "סוג הפגישה" },
  },
  reservationCollect: {
    check_in: { title: "כניסה", blurb: "תמיד נאסף" },
    check_out: { title: "יציאה", blurb: "תמיד נאסף" },
    guests: { title: "אורחים", blurb: "מספר אורחים" },
    unit: { title: "יחידה", blurb: "סוג חדר / וילה" },
    name: { title: "שם", blurb: "שם מלא" },
    phone: { title: "טלפון", blurb: "מספר לחזרה" },
    email: { title: "אימייל", blurb: "לאישור" },
  },
  inbox: {
    decisionLegend: "החלטה",
    approveOption: "אישור",
    needInfoOption: "צריך עוד פרטים",
    notePlaceholder: "הערה שהסוכן ישתמש בה",
    complete: "סיום והמשך",
    bookingApproval: "אישור ביקור",
    reservationApproval: "אישור הזמנת אירוח",
    tasksWaiting: "{count} משימות ממתינות",
    emptyHint: "כשלקוח מבקש נציג, ביקור או אירוח - המשימה תופיע כאן.",
    generalTask: "משימת נציג",
    openChat: "פתיחת סימולטור",
    reason: "סיבה",
    summaryTitle: "סיכום השיחה",
    summaryEmpty: "עדיין אין סיכום - אפשר לפתוח את הצ'אט לשיחה המלאה.",
    summaryWhen: "מועד",
    summaryIntent: "כוונה",
    declineNoteLabel: "הערה ללקוח (אופציונלי)",
    declineNotePlaceholder: "תתווסף מתחת להודעה עם הקידומת ״הערת הנציג״",
    customReplyLabel: "תשובה מותאמת (אופציונלי — לאישור בלבד, במקום התבנית)",
    customReplyPlaceholder: "השאירו ריק לשימוש בתבנית",
    newConversation: "סיים שיחה",
    startConversation: "התחל שיחה חדשה",
    reopenConversation: "פתח שיחה מחדש",
    startDisabledHint: "שיחה הסתיימה",
    conversationEnded: "שיחה הסתיימה",
    reopenDisabledHint: "לא ניתן לפתוח מחדש כשיש שיחה חדשה פתוחה",
    decisionsLockedHint: "לא ניתן לשנות החלטה בשיחה ישנה — נפתחה כבר שיחה חדשה",
    decisionLogAction: "פעולה",
    decisionLogWhen: "מתי",
    decisionLogActor: "מי ביצע",
    decisionLogApproved: "אישר פגישה",
    decisionLogDeclined: "דחה פגישה",
    decisionLogRescheduled: "הציע מועד אחר",
    decisionLogApprovedByCustomer: "הלקוח אישר מועד",
    decisionLogActorAdmin: "אדמין",
    decisionLogActorCustomer: "לקוח",
    decisionLogActorAutomatic: "אוטומטי",
    decisionLogActorGlobalAdmin: "אדמין גלובלי",
    decisionLogPreviousSlot: "מועד קודם",
    decisionLogEmpty: "עדיין אין החלטות מתועדות",
    taskEnteredAt: "נכנסה",
    taskDecidedAt: "הוחלטה",
    taskDecidedBy: "על ידי",
    linkSent: "קישור נשלח",
    linkSentHint: "נשלח ללקוח קישור להשלמת הזמנה עצמית.",
    markRead: "סמן כנקרא",
    markUnread: "סמן כלא נקרא",
    staffPlaceholder: "כתבו ללקוח בתור הנציג…",
    historyTitle: "טופלו",
    waitingTitle: "ממתינים",
    taskOpen: "פתוח",
    taskResolved: "טופל",
    updateDecision: "אפשר לשנות את ההחלטה; הודעה חדשה תישלח בשיחה",
    currentDecision: "החלטה נוכחית",
    changeDecision: "שנה החלטה",
    awaitingCustomer: "ממתין לאישור לקוח",
    awaitingCustomerHint: "הוצע מועד חלופי — ממתינים שהלקוח יאשר בשיחה.",
    customerConfirmed: "הלקוח אישר",
    reasons: {
      support_unresolved: "הסוכן לא הצליח לפתור וביקש נציג.",
      escalation_requested: "הלקוח ביקש לדבר עם נציג אנושי.",
      asked_for_person: "הלקוח ביקש לדבר עם נציג.",
      request_approval: "בקשה ממתינה לאישור",
    },
  },
  meeting: {
    approve: "אישור הביקור",
    decline: "דחייה",
    reschedule: "הצעת מועד חלופי",
    alternativeSlotLabel: "מועד חלופי ללקוח",
    alternativeSlotPlaceholder: "לדוגמה: חמישי ב־12:00",
    visitDefault: "ביקור",
    approved: "אושר",
    rejected: "נדחה",
  },
  reservation: {
    approve: "אישור אירוח",
    decline: "דחייה",
    reschedule: "הצעת תאריכים אחרים",
    checkIn: "כניסה",
    checkOut: "יציאה",
    guests: "אורחים",
    unit: "יחידה",
    alternativeCheckInLabel: "כניסה חלופית",
    alternativeCheckOutLabel: "יציאה חלופית",
    approved: "אושר",
    rejected: "נדחה",
  },
  ops: {
    catalogLegend: "קטלוג (משכפל את הזרימה)",
    afterDoneLegend: "אחרי סיום שיחה",
    ignoreMessages: "התעלם מהודעות חדשות",
    restartFlow: "התחל את הזרימה מחדש",
    fallbackStage: "עבור לשלב גיבוי",
    fallbackStageLabel: "שלב גיבוי",
    noneOption: "(ללא)",
    hitlLegend: "מעורבות אנושית",
    allowHuman: "אפשר העברה לנציג",
    stagesLegend: "שלבים שמותר להעביר מהם",
    intentsLegend: "כוונות שמותר להעביר",
    ownersNeverSee: "בעלי העסק לא רואים דף זה.",
  },
  flow: {
    start: "התחלה",
    afterDone: "אחרי סיום",
    needFields: "שדות נדרשים",
    transitions: "מעברים",
    currentStage: "שלב נוכחי",
    progress: "התקדמות בזרימה",
  },
  leadFields: {
    name: "שם",
    need: "פרטי הפגישה",
    email: "אימייל",
    phone: "טלפון",
    budget: "תקציב",
    intent: "כוונה",
    booking: "הזמנה",
    service: "שירות",
    visit_kind: "סוג ביקור",
    time_preference: "מועד מועדף",
  },
  requestKinds: {
    visit: "ביקור",
    stay: "שהייה",
    showroom: "אולם תצוגה",
    online: "מקוון",
    phone: "שיחת טלפון",
  },
  stages: {
    talk: "שיחה",
    escalate: "העברה לנציג",
    done: "סיום",
    waiting_human: "ממתין לנציג",
    collect: "איסוף פרטים",
    classify: "סיווג",
  },
  intents: {
    sales: "מכירות",
    support: "תמיכה",
    other: "אחר",
  },
  stageTypes: {
    talk: "שיחה",
    collect: "איסוף",
    classify: "סיווג",
    action: "פעולה",
    terminal: "סיום",
  },
  convoStatus: {
    open: "פעיל",
    waiting_human: "ממתין לנציג",
    closed: "סגור",
  },
  restartPolicy: {
    ignore: "התעלם מהודעות",
    restart: "התחל מחדש",
    fallback: "שלב גיבוי",
  },
  actions: {
    request_human: "בקשת נציג",
  },
  pagination: {
    showing: "מציג {from}–{to} מתוך {total}",
    page: "{current} / {total}",
    perPage: "לעמוד",
    prev: "הקודם",
    next: "הבא",
  },
  channels: {
    statusConnected: "מחובר",
    statusDisconnected: "לא מחובר",
    connectStepsTitle: "איך מתחברים",
    stepConnect: "לחצו חיבור וואטסאפ",
    stepVerify: "אשרו ב-Meta Embedded Signup",
    stepLive: "הודעות יגיעו ללידים",
    allConnections: "כל החיבורים",
    whatsAppPrimary: "וואטסאפ - ערוץ ראשי",
    connectedSuccess: "וואטסאפ מחובר בהצלחה",
    instagramConnectedSuccess: "אינסטגרם מחובר בהצלחה",
    notConnectedHint: "חברו את מספר העסק כדי לקבל לידים מוואטסאפ.",
    identity: "חשבון",
    actions: "פעולות",
  },
  demo: {
    leadProfile: "פרטי לקוח",
    simulateAs: "סימולציה כלקוח",
    agentContext: "הקשר הסוכן",
    openFullLead: "פתיחת ליד מלא",
    activeNow: "פעיל עכשיו",
    noLeadSelected: "בחרו לקוח מהרשימה או התחילו בדיקה חדשה",
    contactInfo: "פרטי קשר",
    banner: "סימולטור - אתם הלקוח. וואטסאפ חי נמצא בערוצים.",
  },
  errors: {
    createFailed: "יצירה נכשלה",
    createdClaimOnSignIn:
      "הדייר נוצר. הזמנות Clerk דורשות דומיין מותאם — בקשו מהבעלים להירשם באפליקציה עם אותו אימייל; הגישה תינתן אוטומטית.",
    connectFailed: "החיבור נכשל",
    noAgent: "אין סוכן. הריצו seed לבסיס הנתונים.",
    noTenant: "אין דייר. הריצו seed לבסיס הנתונים.",
    forbidden: "אין לכם הרשאה לדף זה.",
  },
  team: {
    inviteEmail: "אימייל",
    inviteRole: "תפקיד",
    inviteSend: "שליחת הזמנה",
    members: "חברים",
    pendingInvites: "הזמנות ממתינות",
    roleOwner: "בעלים",
    roleAdmin: "אדמין",
    roleMember: "חבר",
    promote: "הפוך לאדמין",
    demote: "הפוך לחבר",
    remove: "הסרה",
    revoke: "ביטול",
    loadFailed: "טעינת הצוות נכשלה",
    empty: "עדיין אין.",
    inviteClaimOnSignIn:
      "נשמר. הזמנות Clerk דורשות דומיין מותאם — בקשו מהם להירשם כאן עם אותו אימייל; הגישה תינתן אוטומטית.",
  },
  crm: {
    stages: {
      new: "חדש",
      talking: "בשיחה",
      qualified: "פרטים התקבלו",
      pending: "ממתין לאישור",
      won: "נסגר",
      lost: "אבוד",
      not_relevant: "לא רלוונטי",
    },
    wonByCapability: { booking: "נקבע", reservations: "הוזמן" },
    tabs: { needs: "צריך אותך", active: "פעילים", won: "נסגרו", closed: "אבוד / לא רלוונטי", all: "הכל" },
    wonWindow: "30 ימים אחרונים",
    cols: { lead: "ליד", stage: "שלב", stand: "איפה זה עומד", followUp: "מעקב", last: "קשר אחרון" },
    reasons: { handoff: "הועבר אליך", approval: "ממתין לאישורך", reminder: "תזכורת", cold: "התקרר" },
    reasonsLong: {
      handoff: "הבוט העביר אליך את השיחה",
      approval: "בקשה ממתינה לאישורך",
      reminder: "תזכורת שקבעת",
      cold: "הליד הפסיק לענות",
    },
    cta: {
      handoff: "ענה בתיבה",
      approval: "בדוק בתיבה",
      reminder: "סמן כבוצע",
      cold: "שלח הודעה",
      coldPhone: "פתח בטלפון",
    },
    them: "הם כתבו",
    us: "אנחנו כתבנו",
    windowLeft: "{h} ש׳ לחלון",
    windowClosed: "חלון סגור",
    windowClosedNote: "חלון 24 השעות נסגר. אפשר לכתוב רק מהטלפון או בתבנית.",
    conversationClosed: "השיחה נסגרה",
    auto: "אוטומטי",
    manual: "ידני",
    autoReasons: {
      first_message: "הודעה ראשונה",
      engaged: "הבוט בשיחה",
      intent: "זוהתה כוונה",
      flow: "לפי התסריט",
      collected: "כל הפרטים נאספו",
      requestPending: "בקשה ממתינה",
      requestApproved: "הבקשה אושרה",
      revived: "הליד כתב שוב",
    },
    revived: "חזר",
    snooze: "דחייה",
    snooze1: "מחר בבוקר",
    snooze3: "בעוד 3 ימים",
    snooze7: "בעוד שבוע",
    snoozed: "נדחה ל{when}",
    nextStep: "הצעד הבא",
    noNextStep: "אין צעד הבא.",
    nextPresets: ["מחר 9:00", "בעוד 3 ימים", "שבוע הבא"],
    nextPlaceholder: "מה הצעד הבא?",
    markDone: "בוצע",
    nextSaved: "הצעד הבא נשמר",
    markedDone: "סומן כבוצע",
    notes: "הערות פנימיות",
    notesHint: "רק הצוות רואה",
    addNote: "הוספת הערה…",
    saveNote: "שמור",
    saveHint: "⌘/Ctrl + Enter",
    pin: "הצמד",
    unpin: "בטל הצמדה",
    deleteNote: "מחק הערה",
    tabsLead: { chat: "שיחה", activity: "פעילות", details: "פרטים" },
    timelineFilters: { all: "הכל", notes: "הערות", stages: "שלבים", requests: "בקשות" },
    timeline: {
      stageAuto: 'השלב שונה ל"{stage}"',
      stageManual: '{actor} שינה/תה את השלב ל"{stage}"',
      note: "{actor} הוסיף/ה הערה",
      nextSet: "{actor} קבע/ה צעד הבא",
      nextDone: "{actor} סימן/ה את הצעד הבא כבוצע",
      snooze: "{actor} דחה/תה ל{when}",
      requestCreated: "נוצרה בקשה",
      requestApprove: "{actor} אישר/ה את הבקשה",
      requestDecline: "{actor} דחה/תה את הבקשה",
      requestReschedule: "{actor} הציע/ה מועד אחר",
      handoffOpened: "הבוט העביר אליך את השיחה",
      handoffResolved: "ההעברה טופלה",
      convoStarted: "השיחה התחילה",
      convoEnded: "השיחה הסתיימה",
      revived: "הליד כתב שוב",
      today: "היום",
      yesterday: "אתמול",
    },
    lostReasons: ["מחיר", "תאריכים", "בחר/ה מקום אחר", "לא ענה/תה", "אחר"],
    notRelevantReasons: ["שירות לא מתאים", "אזור לא מתאים", "מחפש/ת עבודה", "ספאם", "ספק", "אחר"],
    reasonPrompt: "למה? (לא חובה)",
    stageSet: 'השלב שונה ל"{stage}"',
    undo: "ביטול",
    openFull: "פתח עמוד מלא",
    close: "סגור",
    message: "הודעה",
    channelFilter: "ערוץ",
    needsEmptyTitle: "הכל מטופל",
    needsEmpty: "אין פניות שמחכות לך כרגע. נעדכן בוואטסאפ כשמשהו יגיע.",
    emptyTitle: "אין פניות כאן",
    empty: "נסו לשנות את הסינון.",
    loadFailed: "משהו השתבש. נסו שוב.",
    retry: "נסה שוב",
    selected: "{n} נבחרו",
    bulkStage: "שנה שלב",
    bulkSnooze: "דחה",
    bulkRead: "סמן כנקרא",
    clearSelection: "נקה בחירה",
    keysHint: "מקשים: j/k ניווט · Enter פתיחה · Esc סגירה · s שלב · n צעד הבא · z דחייה · / חיפוש",
    search: "חיפוש שם, טלפון, הערה",
    digestTitle: "תקציר יומי",
    digestBlurb: "סיכום בוואטסאפ כל בוקר על הפניות שצריכות אותך.",
    digestEnabled: "שליחת תקציר יומי לחשבון הזה",
    digestHour: "שליחה בשעה",
    digestPhone: "מספר הוואטסאפ שלך",
    digestOptInText: "שלחו לי סיכום יומי בוואטסאפ על פניות שצריכות אותי. אפשר לכבות כאן בכל עת.",
    digestFeatureOff: "התקציר בוואטסאפ עדיין לא הופעל עבור החשבון הזה.",
    saved: "נשמר",
  },
};
