export type UiLang = "he" | "en";

export type LeadStatusId = "new" | "open" | "in_progress" | "won" | "lost";

export type UiCopy = {
  product: string;
  nav: {
    home: string;
    setup: string;
    chat: string;
    leads: string;
    inbox: string;
    channels: string;
    ops: string;
    admin: string;
  };
  langToggle: { he: string; en: string };
  actingAs: (name: string) => string;
  stopActing: string;
  page: {
    homeTitle: string;
    homeBlurb: string;
    homeSetup: string;
    homeChat: string;
    setupTitle: string;
    setupBlurb: string;
    chatTitle: string;
    leadsTitle: string;
    inboxTitle: string;
    channelsTitle: string;
    opsTitle: string;
    adminTitle: string;
  };
  common: {
    save: string;
    saving: string;
    next: string;
    back: string;
    extract: string;
    extracting: string;
    empty: string;
    pending: string;
    demo: string;
    delete: string;
    confirmDeleteDemo: string;
    name: string;
    channel: string;
    status: string;
    stage: string;
    visit: string;
    intent: string;
    openLead: string;
    noLeads: string;
    nothingWaiting: string;
    comingSoon: string;
    connectWhatsApp: string;
    reconnectWhatsApp: string;
    instagram: string;
    whatsapp: string;
    zernioMissing: string;
    connectedNumber: string;
    accountId: string;
    createTenant: string;
    tenantName: string;
    tenantPhone: string;
    openAsTenant: string;
    adminUnlock: string;
    adminSecret: string;
    unlock: string;
    visitsWaiting: string;
    captured: string;
    conversation: string;
    flow: string;
    customers: string;
    newChat: string;
    knowledge: string;
    business: string;
    done: string;
    step: (n: number, total: number) => string;
  };
  status: Record<LeadStatusId, string>;
};
