export type UiLang = "he" | "en";

export type LeadStatusId = "new" | "open" | "in_progress" | "won" | "lost";

export type CatalogUiId = "inbox" | "book" | "faq";

export type UiCopy = {
  product: string;
  nav: {
    home: string;
    setup: string;
    chat: string;
    leads: string;
    inbox: string;
    channels: string;
    ops: string;
    admin: string;
  };
  langToggle: { he: string; en: string };
  actingAs: string;
  stopActing: string;
  page: {
    homeTitle: string;
    homeBlurb: string;
    homeSetup: string;
    homeChat: string;
    setupTitle: string;
    setupBlurb: string;
    chatTitle: string;
    leadsTitle: string;
    inboxTitle: string;
    channelsTitle: string;
    opsTitle: string;
    adminTitle: string;
  };
  home: {
    quickSetup: string;
    quickChat: string;
    quickLeads: string;
    quickInbox: string;
    quickChannels: string;
    tenantLabel: string;
  };
  common: {
    save: string;
    saving: string;
    next: string;
    back: string;
    extract: string;
    extracting: string;
    empty: string;
    pending: string;
    demo: string;
    delete: string;
    confirmDeleteDemo: string;
    name: string;
    channel: string;
    status: string;
    stage: string;
    visit: string;
    intent: string;
    openLead: string;
    noLeads: string;
    nothingWaiting: string;
    comingSoon: string;
    connectWhatsApp: string;
    reconnectWhatsApp: string;
    instagram: string;
    whatsapp: string;
    zernioMissing: string;
    connectedNumber: string;
    accountId: string;
    createTenant: string;
    tenantName: string;
    tenantPhone: string;
    openAsTenant: string;
    adminUnlock: string;
    adminSecret: string;
    unlock: string;
    visitsWaiting: string;
    captured: string;
    conversation: string;
    flow: string;
    customers: string;
    newChat: string;
    knowledge: string;
    business: string;
    done: string;
    stepOf: string;
    enabled: string;
    disabled: string;
    on: string;
    off: string;
    approve: string;
    decline: string;
    send: string;
    sending: string;
    need: string;
    phone: string;
    email: string;
    version: string;
    menu: string;
  };
  status: Record<LeadStatusId, string>;
  roles: {
    lead: string;
    agent: string;
    human: string;
  };
  chat: {
    emptyThread: string;
    placeholder: string;
    waitingHuman: string;
    pausedForHuman: string;
    startNew: string;
    noIntro: string;
    flowLabel: string;
    languageLabel: string;
    sendFailed: string;
  };
  onboard: {
    agentLanguageLegend: string;
    agentLanguageHint: string;
    knowledgeHint: string;
    knowledgePlaceholder: string;
    dropzoneIdle: string;
    dropzoneBusy: string;
    dropInvalid: string;
    extractFailed: string;
    noLlm: string;
    saveFailed: string;
    businessHint: string;
    fieldName: string;
    fieldPhone: string;
    fieldIntro: string;
    fieldIntroPlaceholder: string;
    fieldAddress: string;
    fieldAddressPlaceholder: string;
    fieldHours: string;
    fieldHoursPlaceholder: string;
    fieldBookingRequest: string;
    fieldBookingApproved: string;
    fieldBookingRejected: string;
    templatesHint: string;
    fieldIdleDays: string;
    idleHint: string;
    doneHint: string;
    catalogLegend: string;
    collectLegend: string;
    collectHint: string;
  };
  catalog: Record<CatalogUiId, { title: string; blurb: string }>;
  chatLanguage: Record<"multi" | "en" | "he", { title: string; blurb: string }>;
  bookingCollect: Record<string, { title: string; blurb: string }>;
  inbox: {
    decisionLegend: string;
    approveOption: string;
    needInfoOption: string;
    notePlaceholder: string;
    complete: string;
    bookingApproval: string;
  };
  meeting: {
    approve: string;
    decline: string;
    visitDefault: string;
  };
  ops: {
    catalogLegend: string;
    afterDoneLegend: string;
    ignoreMessages: string;
    restartFlow: string;
    fallbackStage: string;
    fallbackStageLabel: string;
    noneOption: string;
    hitlLegend: string;
    allowHuman: string;
    stagesLegend: string;
    intentsLegend: string;
    ownersNeverSee: string;
  };
  flow: {
    start: string;
    afterDone: string;
    needFields: string;
    transitions: string;
  };
  errors: {
    badSecret: string;
    createFailed: string;
    connectFailed: string;
    noAgent: string;
    noTenant: string;
  };
};
